### ISSUE TITLE
ДЗ2

### ISSUE THREAD

**Issue by anrom7** [maxymkuz/Sports-predictor#2]
README.md - ?
у вигляді веб-застосунку чи телеграм-бота - це не вимога
можна знайти тут. - а де це тут?
а Ви які дані з 62 використовуєте ?
код відсутній

**Comment by maxymkuz** [comment]
Дякую, виправив. Щодо даних, то планую використати всі 62 критерії, і якщо якісь не будуть корелюватись з результатом згідно моделі, то буду їх позбуватись.
Приклад використання знаходився у файлі data_exploration.ipynb
